# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Z156\PycharmProjects\untitled2\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5 import NavigationToolbar2QT as NavigationToolbar
from pltForWidget import plt_and__canavas_animation
t = 1
time_bool=False

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 933)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(400, 700))
        self.widget.setMaximumSize(QtCore.QSize(2000, 2000))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_8.setSizeIncrement(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_9.setSizeIncrement(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_10.setSizeIncrement(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PauseStart = QtWidgets.QPushButton(self.centralwidget)
        self.PauseStart.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.PauseStart.setFont(font)
        self.PauseStart.setObjectName("PauseStart")
        self.verticalLayout.addWidget(self.PauseStart)
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Reset.setFont(font)
        self.Reset.setObjectName("Reset")
        self.verticalLayout.addWidget(self.Reset)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(100, 60))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_E0 = QtWidgets.QLabel(self.centralwidget)
        self.label_E0.setMinimumSize(QtCore.QSize(50, 0))
        self.label_E0.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_E0.setFont(font)
        self.label_E0.setObjectName("label_E0")
        self.verticalLayout_4.addWidget(self.label_E0)
        self.label_E1 = QtWidgets.QLabel(self.centralwidget)
        self.label_E1.setMinimumSize(QtCore.QSize(50, 0))
        self.label_E1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_E1.setFont(font)
        self.label_E1.setObjectName("label_E1")
        self.verticalLayout_4.addWidget(self.label_E1)
        self.label_E1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_E1_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_E1_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_E1_2.setFont(font)
        self.label_E1_2.setObjectName("label_E1_2")
        self.verticalLayout_4.addWidget(self.label_E1_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineT = QtWidgets.QLineEdit(self.centralwidget)
        self.lineT.setMinimumSize(QtCore.QSize(70, 25))
        self.lineT.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineT.setObjectName("lineT")
        self.verticalLayout_5.addWidget(self.lineT)
        self.lineE0 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineE0.setMinimumSize(QtCore.QSize(70, 25))
        self.lineE0.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineE0.setObjectName("lineE0")
        self.verticalLayout_5.addWidget(self.lineE0)
        self.lineE1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineE1.setMinimumSize(QtCore.QSize(70, 25))
        self.lineE1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineE1.setObjectName("lineE1")
        self.verticalLayout_5.addWidget(self.lineE1)
        self.line_t = QtWidgets.QLineEdit(self.centralwidget)
        self.line_t.setMinimumSize(QtCore.QSize(70, 25))
        self.line_t.setMaximumSize(QtCore.QSize(70, 16777215))
        self.line_t.setObjectName("line_t")
        self.verticalLayout_5.addWidget(self.line_t)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(50, 0))
        self.label_14.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.lineFi_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFi_2.setMinimumSize(QtCore.QSize(70, 25))
        self.lineFi_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineFi_2.setObjectName("lineFi_2")
        self.horizontalLayout_13.addWidget(self.lineFi_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.lineFi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFi.setMinimumSize(QtCore.QSize(70, 25))
        self.lineFi.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineFi.setObjectName("lineFi")
        self.horizontalLayout_12.addWidget(self.lineFi)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.pushGen = QtWidgets.QPushButton(self.centralwidget)
        self.pushGen.setMinimumSize(QtCore.QSize(100, 0))
        self.pushGen.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushGen.setFont(font)
        self.pushGen.setStyleSheet("\n"
"background-color: rgb(149, 255, 83);\n"
"background-color: rgb(255, 111, 118);")
        self.pushGen.setObjectName("pushGen")
        self.verticalLayout_7.addWidget(self.pushGen)
        self.pushGen_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushGen_2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushGen_2.setFont(font)
        self.pushGen_2.setStyleSheet("\n"
"border-color: rgb(255, 0, 0);")
        self.pushGen_2.setObjectName("pushGen_2")
        self.verticalLayout_7.addWidget(self.pushGen_2)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_3.setSizeIncrement(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_4.setSizeIncrement(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setSizeIncrement(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMinimumSize(QtCore.QSize(90, 0))
        self.label_11.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineSpeed = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSpeed.setMinimumSize(QtCore.QSize(70, 25))
        self.lineSpeed.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineSpeed.setObjectName("lineSpeed")
        self.verticalLayout_8.addWidget(self.lineSpeed)
        self.lineK = QtWidgets.QLineEdit(self.centralwidget)
        self.lineK.setMinimumSize(QtCore.QSize(70, 25))
        self.lineK.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineK.setObjectName("lineK")
        self.verticalLayout_8.addWidget(self.lineK)
        self.lineP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineP.setMinimumSize(QtCore.QSize(70, 25))
        self.lineP.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineP.setObjectName("lineP")
        self.verticalLayout_8.addWidget(self.lineP)
        self.lineRandom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineRandom.setMinimumSize(QtCore.QSize(50, 25))
        self.lineRandom.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineRandom.setObjectName("lineRandom")
        self.verticalLayout_8.addWidget(self.lineRandom)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_L = QtWidgets.QLabel(self.centralwidget)
        self.label_L.setMinimumSize(QtCore.QSize(50, 0))
        self.label_L.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_L.setFont(font)
        self.label_L.setObjectName("label_L")
        self.horizontalLayout_11.addWidget(self.label_L)
        self.line_L = QtWidgets.QLineEdit(self.centralwidget)
        self.line_L.setMinimumSize(QtCore.QSize(70, 25))
        self.line_L.setMaximumSize(QtCore.QSize(70, 16777215))
        self.line_L.setObjectName("line_L")
        self.horizontalLayout_11.addWidget(self.line_L)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.lineW = QtWidgets.QLineEdit(self.centralwidget)
        self.lineW.setMinimumSize(QtCore.QSize(70, 25))
        self.lineW.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineW.setObjectName("lineW")
        self.horizontalLayout_10.addWidget(self.lineW)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMinimumSize(QtCore.QSize(50, 0))
        self.label_12.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.line_m = QtWidgets.QLineEdit(self.centralwidget)
        self.line_m.setMinimumSize(QtCore.QSize(70, 25))
        self.line_m.setMaximumSize(QtCore.QSize(70, 16777215))
        self.line_m.setObjectName("line_m")
        self.horizontalLayout_9.addWidget(self.line_m)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.pushRandom = QtWidgets.QPushButton(self.centralwidget)
        self.pushRandom.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushRandom.setFont(font)
        self.pushRandom.setObjectName("pushRandom")
        self.verticalLayout_3.addWidget(self.pushRandom)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_canavas()
        self.connect_buttons()

        #self.timer = QtCore.QTimer()
        #self.timer.timeout.connect(self.timer_func)
    def connect_buttons(self):
        self.PauseStart.clicked.connect(self.event_pause)
        self.Reset.clicked.connect(self.event_reset)

        self.pushGen_2.clicked.connect(self.event_input_Gen_2)
        self.pushRandom.clicked.connect(self.event_input_set)
        self.pushGen.clicked.connect(self.event_input_Gen)


        self.lineW.setText(str(self.Canavas_and_animation.s.w))
        self.lineT.setText(str(self.Canavas_and_animation.s.T))
        self.lineE0.setText(str(self.Canavas_and_animation.s.E0))
        self.lineE1.setText(str(self.Canavas_and_animation.s.E1))
        self.lineSpeed.setText(str(self.Canavas_and_animation.s.h))
        self.lineK.setText(str(self.Canavas_and_animation.s.k))
        self.lineP.setText(str(self.Canavas_and_animation.s.q)) #&&&&&&&
        self.lineRandom.setText(str(self.Canavas_and_animation.s.Random))
        self.line_L.setText(str(self.Canavas_and_animation.s.L))
        self.line_m.setText(str(self.Canavas_and_animation.s.m))
        self.line_t.setText(str(self.Canavas_and_animation.s.sig))
        self.lineFi.setText(str(self.Canavas_and_animation.s.Fi))
        self.lineFi_2.setText(str(self.Canavas_and_animation.s.t1))





    def event_input_Gen(self):
        self.Canavas_and_animation.s.Gen ^= True
        if(self.Canavas_and_animation.s.Gen):
            self.pushGen.setStyleSheet('QPushButton {background-color: rgb(149, 255, 83);}')
        else:
            self.pushGen.setStyleSheet('QPushButton {background-color: rgb(255, 111, 118);}')
    def event_input_Gen_2(self):

        self.Canavas_and_animation.s.T = float(self.lineT.text())
        self.Canavas_and_animation.s.E0 = float(self.lineE0.text())
        self.Canavas_and_animation.s.E1 = float(self.lineE1.text())
        self.Canavas_and_animation.s.sig = float(self.line_t.text())
        self.Canavas_and_animation.s.Fi = float(self.lineFi.text())
        self.Canavas_and_animation.s.t1 = float(self.lineFi_2.text())

    def event_input_set(self):
        self.Canavas_and_animation.s.L = float(self.line_L.text())
        self.Canavas_and_animation.s.m = float(self.line_m.text())
        self.Canavas_and_animation.s.w = float(self.lineW.text())
        self.Canavas_and_animation.s.h = float(self.lineSpeed.text())
        self.Canavas_and_animation.s.K = float(self.lineK.text())
        self.Canavas_and_animation.s.q = float(self.lineP.text())
        self.Canavas_and_animation.s.Random = float(self.lineRandom.text())
    def event_reset(self,event):
        self.Canavas_and_animation.start(event)
        self.Canavas_and_animation.s.reset()
        self.Canavas_and_animation.reset_mas_for_plot()




    def event_pause(self,event):
        self.Canavas_and_animation.start(event)
    #    self.event_timer_start()
    #def event_timer_start(self):
    #    if(not time_bool):
    #        self.timer.start(1000)
    #def timer_func(self):
     #   self.lab_time.setText("t=" + str(self.Canavas_and_animation.s.t[-1]))
    def add_canavas(self):
        self.companovca_for_mpl = QtWidgets.QVBoxLayout(self.widget)
        self.Canavas_and_animation = plt_and__canavas_animation()  # Создание класса с plt
        self.companovca_for_mpl.addWidget(self.Canavas_and_animation)
        self.toolbar = NavigationToolbar(self.Canavas_and_animation, MainWindow)
        self.companovca_for_mpl.addWidget(self.toolbar)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pendulum"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; text-decoration: underline;\">Control Panel</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#005500;\">  Fм=𝐹⃗o+𝐹⃗1∙𝑒^((𝑡−𝑡1)^2)/𝛕)∙𝐶𝑜𝑠(2𝜋𝑓𝑡+𝜑)+𝐹⃗ш  </span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">X</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">Fm</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#5500ff;\">V</span></p></body></html>"))
        self.PauseStart.setText(_translate("MainWindow", "старт/стоп"))
        self.Reset.setText(_translate("MainWindow", "очистить"))
        self.label_7.setText(_translate("MainWindow", "f"))
        self.label_E0.setText(_translate("MainWindow", "E0"))
        self.label_E1.setText(_translate("MainWindow", "E1"))
        self.label_E1_2.setText(_translate("MainWindow", "τ"))
        self.label_14.setText(_translate("MainWindow", "t1"))
        self.label_13.setText(_translate("MainWindow", "φ"))
        self.pushGen.setText(_translate("MainWindow", "Генератор"))
        self.pushGen_2.setText(_translate("MainWindow", "Принять"))
        self.label_3.setText(_translate("MainWindow", "speed"))
        self.label_4.setText(_translate("MainWindow", "K"))
        self.label_5.setText(_translate("MainWindow", "p"))
        self.label_11.setText(_translate("MainWindow", "Random(F)"))
        self.label_L.setText(_translate("MainWindow", "𝜆"))
        self.label_6.setText(_translate("MainWindow", "w"))
        self.label_12.setText(_translate("MainWindow", "m"))
        self.pushRandom.setText(_translate("MainWindow", "Принять"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
